// Regenerate lib/client.js (from src/client.js) with a Simplified -> Traditional (Taiwan) table for the
// DSH Web client's zh text, so the site UI can run in 繁體中文 without patching
// DSH. Run after upgrading DSH (the table is keyed on its exact strings):
//
//   npm install --no-save opencc-js@1.4.2      (MIT AND Apache-2.0)
//   node tools/build-zh-tw.mjs <dir containing the DSH client bundles...>
//
// Output: exact-string map (every zh literal found in the bundles) plus a
// character table for text assembled at runtime. Both come from OpenCC's
// cn -> twp (Taiwan phrases) conversion, then the local wording overrides below.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const OpenCC = require("opencc-js");
const toTw = OpenCC.Converter({ from: "cn", to: "twp" });

// Taiwan product wording where OpenCC's generic conversion reads as mainland.
const OVERRIDES = [
  ["會話", "對話"], ["智慧體", "代理"], ["提供商", "供應商"], ["自定義", "自訂"],
  ["配置檔案", "設定檔"], ["暫無", "尚無"], ["新建", "新增"], ["插話傳送", "插話送出"],
  ["排隊傳送", "排隊送出"], ["許可權", "權限"], ["當前", "目前"], ["字號", "字級"],
  ["傳送", "送出"], ["DeepSeek Harness", "Swarm"],
];
const polish = (s) => OVERRIDES.reduce((text, [a, b]) => text.replaceAll(a, b), toTw(s));

function* files(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* files(full);
    else if (entry.name === "client.js" && full.includes(`${path.sep}lib${path.sep}`)) yield full;
  }
}

const roots = process.argv.slice(2);
if (roots.length === 0) throw new Error("usage: build-zh-tw.mjs <bundle dir>...");
const literal = /"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'/g;
const han = /[\u3400-\u9fff]/;
const exact = {};
const chars = new Set();
for (const root of roots) for (const file of files(root)) {
  const source = fs.readFileSync(file, "utf8");
  for (const match of source.matchAll(literal)) {
    if (!han.test(match[0])) continue;
    let value;
    try { value = JSON.parse(match[0][0] === "'" ? `"${match[0].slice(1, -1).replaceAll('"', '\\"')}"` : match[0]); }
    catch { continue; }
    const converted = polish(value);
    if (converted !== value) exact[value] = converted;
    for (const ch of value) if (han.test(ch)) chars.add(ch);
  }
}
const table = {};
for (const ch of [...chars].sort()) {
  const converted = toTw(ch);
  if (converted !== ch && [...converted].length === 1) table[ch] = converted;
}
const sorted = Object.fromEntries(Object.entries(exact).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
const data = JSON.stringify({ EXACT: sorted, CHARS: table });
const template = fs.readFileSync(new URL("../src/client.js", import.meta.url), "utf8");
if (!template.includes("__ZH_TW__")) throw new Error("src/client.js lost its __ZH_TW__ placeholder");
const out = "// GENERATED by tools/build-zh-tw.mjs from src/client.js and the DSH client bundles\n"
  + "// (OpenCC cn->twp, MIT AND Apache-2.0, plus local Taiwan wording). Do not edit.\n"
  + template.replace("__ZH_TW__", () => data);
fs.writeFileSync(new URL("../lib/client.js", import.meta.url), out);
console.log(`exact ${Object.keys(sorted).length}, chars ${Object.keys(table).length}, ${out.length} bytes`);
